config/routes.rb
Rails.application.routes.draw do
  devise_for :users
resources :doctors
root 'doctors#index'
resources :doctors do
  resources :patients
end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/doctor.rb
class Doctor < ApplicationRecord
  belongs_to :user
  has_many :patients
end

app/models/patient.rb
class Patient < ApplicationRecord
  belongs_to :doctor
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         has_many :doctors
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  # def after_sign_in_path_for(resource)
  #   profile_path(resource)
  # end
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  before_action :authenticate_user!, except: [:show]
  before_action :set_doctor, only: [:show, :edit, :update, :destroy]
  def index
    @doctors = Doctor.all.order("created_at Desc")
  end

  def show

  end

  def new
    @doctor =current_user.doctors.build
  end

  def create

    @doctor = current_user.doctors.build(doctor_params)
    if @doctor.save!
      redirect_to root_path, notice: "Doctor saved!"
    else
      render 'new'
    end
  end

  def edit

  end

  def update
    if @doctor.update(doctor_params)
      redirect_to root_path, notice: "updated!"
    else render 'edit'
    end
  end

  def destroy
    @doctor.destroy
    redirect_to root_path, notice: "record deleted! "
  end

  private
  def set_doctor
    @doctor = Doctor.find(params[:id])
  end
  def doctor_params
    params.require(:doctor).permit(:name)
  end

end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_doctor, only: [:index, :show, :new, :create, :destroy]
  before_action :set_patient, only: [:show, :destroy]
  def index
    @patients = @doctor.patients
  end

  def show
    end

  def new
    @patient = @doctor.patients.build
  end

  def create
    @patient = @doctor.patients.create(patient_params)
    if @patient.save
        redirect_to doctor_path(@doctor), notice: "Patient Registered!"
    else
      render :new
    end
  end

  def set_doctor
    @doctor = Doctor.find(params[:doctor_id])
  end

  def set_patient
    @patient = Patient.find(params[:id])
  end

  def destroy
    @patient.destroy
    redirect_to doctor_path(@doctor), notice: "Patient deleted!"
  end

  private
  def patient_params
    params.require(:patient).permit(:name, :sex, :insurance_N0)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/doctors/_form.html.erb
<div class="panel-body">
  <%= form_for @doctor do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <%= f.submit %>
  <%end%>
</div>

app/views/doctors/edit.html.erb
<div class="panel-heading">
  <h2>Edit Doctor</h2>
</div>
<%= render 'form' %>

app/views/doctors/index.html.erb
<h2>Available Doctors</h2>
  <% @doctors.each do |doctor| %>
  <div class="panel-body">
  <p><%= link_to doctor.name, doctor %></p><%= link_to 'Edit', edit_doctor_path(doctor) %>
  <%= link_to "Delete", doctor_path(doctor), method: :delete, data: {confirm: "Are you sure?"} %>
  </div>
  <% end %>
  <div><%=link_to "[New Doctor]", new_doctor_url%></div>

app/views/doctors/new.html.erb
<div class="panel-heading">
  <h2>Add Doctor</h2>
</div>
<%= render 'form' %>

app/views/doctors/show.html.erb
<h2><%=@doctor.name%></h2>
<%= render 'patients/index' %>
<hr>
<%= link_to "[Register new Patient]", new_doctor_patient_path(@doctor)%>
<%= link_to "[Home]", root_path%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HospAppointment</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "devise/shared/navbar" %>

 <p class="notice"><%= notice %></p>
 <p class="alert"><%= alert %></p>

 <div class="container">
   <%= yield %>
 </div>
  </body>
</html>

app/views/patients/_form.html.erb
<%= form_for ([@doctor, @patient]) do |f|  %>
<p><%= f.label:name %></p>
<p><%= f.text_field:name%></p><br>
<p><%= f.label:sex %></p>
<p><%= f.text_field:sex %></p><br>
<p><%= f.label:insurance_N0 %></p>
<p><%= f.text_field:insurance_N0 %></p>
<p><%= f.submit %></p>
<% end %>

app/views/patients/_index.html.erb
<u>My Patients</u>
<ul>
  <li><% @doctor.patients.each do |patient| %>
  <p><%= link_to patient.name, doctor_patient_path(@doctor, patient) %></P>
  <% end %></li>
</ul>

app/views/patients/new.html.erb
<h3>Add new Patient</h3>
<%= render 'form' %>

app/views/patients/show.html.erb
<p><%= @patient.name %></p>
<%= link_to "Back", doctor_path(@doctor) %>
<%= link_to "Delete", doctor_patient_path(@doctor, @patient), method: :delete, data: {confirm: "Are you sure?"} %>